version: '3.8'
services:
  server:
    image: distributed-turn
    privileged: true 
    cap_add:
      - NET_ADMIN
    command: tail -f /dev/null #python3 python3_codes/udp_server.py
    networks:
      - PUBLIC_NET
    environment:
      - SERVER_PORT=5000
      - SERVER_IP=15.0.0.3

networks:
  PUBLIC_NET:
    external: true
