version: '3.8'
services:
  central_server:
    image: distributed-turn
    networks:
      PUBLIC_NET:
        # Assign a fixed IP if desired. Otherwise you can omit ipv4_address.
        # For example:
        ipv4_address: 15.0.0.3
    environment:
      - SERVER_PORT=50000
      - PYTHONPATH=/app
    command: tail -f /dev/null
    # Expose the UDP port for external debugging, if you wish
    ports:
      - "50000:50000/udp"

  peer_a:
    image: distributed-turn
    networks:
      PUBLIC_NET:
        ipv4_address: 15.0.0.10
    environment:
      - PYTHONPATH=/app
    command: tail -f /dev/null
    cap_add:
      - NET_ADMIN
    depends_on:
      - central_server

  peer_b:
    image: distributed-turn
    networks:
      PUBLIC_NET:
        ipv4_address: 15.0.0.11
    environment:
      - PYTHONPATH=/app
    command: tail -f /dev/null
    cap_add:
      - NET_ADMIN
    depends_on:
      - central_server

  relay_peer:
    image: distributed-turn
    networks:
      PUBLIC_NET:
        ipv4_address: 15.0.0.12
    environment:
      - PYTHONPATH=/app
    command: tail -f /dev/null
    cap_add:
      - NET_ADMIN
    depends_on:
      - central_server

networks:
  PUBLIC_NET:
    # If you already created this network externally, ensure it exists or remove `external: true`.
    external: true
    # Alternatively, define a custom subnet here if you like:
    # driver: bridge
    # ipam:
    #   config:
    #     - subnet: 15.0.0.0/16
