version: '3.8'

services:
  central_server:
    image: distributed-turn
    networks:
      - PUBLIC_NET
    command: tail -f /dev/null
    environment:
      - SERVER_PORT=5000
  
  peer_a:
    image: distributed-turn
    networks:
      - NAT_NET1
    command: tail -f /dev/null
    depends_on:
      - nat_a
      - central_server
  
  peer_b:
    image: distributed-turn
    networks:
      - NAT_NET2
    command: tail -f /dev/null
    depends_on:
      - nat_b
      - central_server
  
  relay_peer:
    image: distributed-turn
    networks:
      - PUBLIC_NET
    command: tail -f /dev/null
    depends_on:
      - central_server

  nat_a:
    image: distributed-turn
    privileged: true
    networks:
      - NAT_NET1
      - PUBLIC_NET
    cap_add:
      - NET_ADMIN
    command: ./startup_scripts/nat_startup.sh symmetric
  
  nat_b:
    image: distributed-turn
    privileged: true
    networks:
      - NAT_NET2
      - PUBLIC_NET
    cap_add:
      - NET_ADMIN
    command: ./startup_scripts/nat_startup.sh symmetric

networks:
  PUBLIC_NET:
    external: true
  NAT_NET1:
    external: true
  NAT_NET2:
    external: true